objc: true
sdk: iphonesimulator
source_directory: XCDYouTubeKit
framework_root: .
umbrella_header: XCDYouTubeKit/XCDYouTubeKit.h
module: XCDYouTubeKit
module_version: 2.15.2

author: Cédric Luthi
author_url: https://twitter.com/0xced

readme: README.md
github_url: https://github.com/LMTKit/XCDYouTubeKit
github_file_prefix: https://github.com/LMTKit/XCDYouTubeKit/tree/2.15.2/XCDYouTubeKit
